{% set name = "pymupdf" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymupdf/PyMuPDF/archive/{{ version }}.tar.gz
  sha256: 920d08215c7bbb554b3a4c2aa688be442ae1bd23fdd3bce92dc5b48519286c93

build:
  skip: true  # [not linux]
  script: PYMUPDF_SETUP_MUPDF_BUILD="" PYMUPDF_SETUP_MUPDF_REBUILD=0 PYMUPDF_MUPDF_LIB="$PREFIX/lib" PYMUPDF_INCLUDES="$PREFIX/include,$PREFIX/include/mupdf,$PREFIX/include/freetype2" {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
  host:
    - python
    - pip
    - mupdf ={{ version }}
    - libjpeg-turbo
    - jbig2dec
    - libgumbo
    - harfbuzz
    - openjpeg
  run:
    - python
    - mupdf ={{ version }}

test:
  imports:
    - fitz
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.
  home: https://github.com/pymupdf/pymupdf
  license: AGPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - jan-janssen
