context:
  name: pymupdf
  version: "1.26.7"
  mupdf_version: "1.26.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/pymupdf/PyMuPDF/archive/${{ version }}.tar.gz
  sha256: f605e11bb459c258ff04e0003c901cd70b16d3f8f172cd3d11a127debf28d3e3
  patches:
    - system-mupdf.patch

build:
  number: 0
  script:
    - if: unix
      then: LD="$CXX" PYMUPDF_SETUP_MUPDF_BUILD="" PYMUPDF_SETUP_MUPDF_REBUILD=0 PYMUPDF_MUPDF_LIB="$PREFIX/lib" PYMUPDF_INCLUDES="$PREFIX/include:$PREFIX/include/mupdf:$PREFIX/include/freetype2" pip install . -vv --no-deps --no-build-isolation
    - if: win
      then: |
        set "CC="
        set "CXX="
        set "LD="
        set "PYMUPDF_SETUP_MUPDF_BUILD=system"
        set "PYMUPDF_SETUP_MUPDF_REBUILD=0"
        set "PYMUPDF_MUPDF_LIB=%LIBRARY_LIB%"
        set "PYMUPDF_INCLUDES=%LIBRARY_INC%\mupdf"
        pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - swig
    - mupdf =${{ mupdf_version }}
  host:
    - python
    - pip
    - setuptools
    - mupdf =${{ mupdf_version }}
  run:
    - python
    - mupdf =${{ mupdf_version }}

tests:
  - python:
      imports:
        - fitz
        - pymupdf
      pip_check: true

about:
  summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.
  license: AGPL-3.0-or-later
  license_file: COPYING
  homepage: https://github.com/pymupdf/pymupdf

extra:
  recipe-maintainers:
    - jan-janssen
    - moritzwilksch
    - benmoss
