context:
  name: pymupdf
  version: 1.24.12

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/pymupdf/PyMuPDF/archive/${{ version }}.tar.gz
  sha256: 5674527e688c6bca7cb992aa79e250a61903114ac699bb08a9ba54f1fc33af5a

build:
  number: 0
  skip:
    - not linux
  script: PYMUPDF_SETUP_MUPDF_BUILD="" PYMUPDF_SETUP_MUPDF_REBUILD=0 PYMUPDF_MUPDF_LIB="$PREFIX/lib" PYMUPDF_INCLUDES="$PREFIX/include -I$PREFIX/include/mupdf -I$PREFIX/include/freetype2" pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - swig
    - mupdf =1.24.10
  host:
    - python
    - pip
    - setuptools
    - mupdf =1.24.10
  run:
    - python
    - mupdf =1.24.10

tests:
  - python:
      imports:
        - fitz
        - pymupdf
      pip_check: true
  - requirements:
      run:
        - pip
    script: pip check

about:
  summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.
  license: AGPL-3.0-or-later
  license_file: COPYING
  homepage: https://github.com/pymupdf/pymupdf

extra:
  recipe-maintainers:
    - jan-janssen
    - moritzwilksch
