context:
  name: pymupdf
  version: "1.27.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/pymupdf/PyMuPDF/archive/${{ version }}.tar.gz
  sha256: 26760a638cd0f8a64ce7d0a3a78d4df8855de2c8a0c59b39b77a689f61af91d7

build:
  number: 0
  script:
    - if: unix
      then: PYMUPDF_SETUP_MUPDF_BUILD="" PYMUPDF_SETUP_MUPDF_REBUILD=0 PYMUPDF_MUPDF_LIB="$PREFIX/lib" PYMUPDF_INCLUDES="$PREFIX/include -I$PREFIX/include/mupdf -I$PREFIX/include/freetype2" pip install . -vv --no-deps --no-build-isolation
    - if: win
      then: |
        set PYMUPDF_SETUP_MUPDF_BUILD=
        set PYMUPDF_SETUP_MUPDF_REBUILD=0
        set PYMUPDF_MUPDF_LIB=%LIBRARY_LIB%
        set PYMUPDF_INCLUDES=%LIBRARY_INC% -I%LIBRARY_INC%\mupdf -I%LIBRARY_INC%\freetype2
        pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - swig
    - mupdf =1.27.2
  host:
    - python
    - pip
    - setuptools
    - mupdf =1.27.2
  run:
    - python
    - mupdf =1.27.2

tests:
  - python:
      imports:
        - fitz
        - pymupdf
      pip_check: true

about:
  summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.
  license: AGPL-3.0-or-later
  license_file: COPYING
  homepage: https://github.com/pymupdf/pymupdf

extra:
  recipe-maintainers:
    - jan-janssen
    - moritzwilksch
